---
deployment:
  tasks:
    - export DEPLOYPATH=/home/trolpdpy/api.datahub.troloppe.com;

    # Copy all other files to deployment path
    - /bin/cp -r * ${DEPLOYPATH};

    # Navigate to deployement path
    - /bin/cd ${DEPLOYPATH};

    # Install Composer Dependencies
    - /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader;

    # Generate an application key
    - /usr/local/bin/php artisan key:generate;

    # Run database migrations
    - if [ ! -f ${DEPLOYPATH}/.deployed ]; 
        then 

        # With seeder on initial deployment
        - /usr/local/bin/php artisan migrate --force --seed; 
      else

        # Without seeder on subsequent deployments
        - /usr/local/bin/php artisan migrate --force; 
      fi

    # Clear and cache config
    - /usr/local/bin/php artisan optimize;
    - /usr/local/bin/php artisan filament:clear-cached-components;
    - /usr/local/bin/php artisan filament:cache-components;
    - /usr/local/bin/php artisan icons:clear ;
    - /usr/local/bin/php artisan icons:cache;

    # Set Permissions
    - /bin/find ${DEPLOYPATH} -type f -exec chmod 644 {}\;
    - /bin/find ${DEPLOYPATH} -type f -exec chmod 755 {}\;
    - /bin/chown -R ${USER}:${USER} ${DEPLOYPATH};
    - /bin/chmod -R 775 ${DEPLOYPATH}/storage; 
    - /bin/chmod -R 775 ${DEPLOYPATH}/bootstrap/cache; 

    # Create Admin User
    - if [ ! -f ${DEPLOYPATH}/.deployed ]; 
        then 
        - /usr/local/bin/php artisan app:create-filament-user; 
        - touch ${DEPLOYPATH}/.deployed;
      fi



